language: node_js
node_js: lts/*
cache:
  npm: false
before_script: 
script:
- yarn install
- yarn build
deploy:
  local_dir: ".vuepress/dist/"
  provider: pages
  skip_cleanup: true
  name: Dortania Bot
  email: bot@dortania.ml
  keep_history: true
  on:
    branch: master
  target_branch: gh-pages
  github_token:
    secure: aPmHbgCoyZ1Gsvth5HEAX44EGGrsEbG+wFvrLWuIWoBumVhmce181NoxMC7+zs2dcxYocXNUVGt50f9jOYk/FZZ0wJUg17uAv0buMPHvxA4zicTWNEwRvrSLX+Qv0g62f5UCWrmubnAsD/slvD/O06a3Z8JUa2qGMbMLE9nAL+Js553TgbHyvWFto7bsuOS8CHTPoxu7/A2/5TGv+Y6aR7Rk6LVaA3wW2GFuvO/A7B24IhvPMwoVlrXMLCMDZbxNoRoHIRNUscp4aJKzuS6agKlSHo1hdi1lcI9E7rbiL7bNqA5D4sJbNNYEqIUZ09EEhQ6V9ri7yKB1h+zGw4alY9jIUOHWk8RFvzX1m1xpAZdq6I+EcnJVhTYm+ujTgj/HJPtqCtSUmI1yHWPVPnOQ33m99ddkqC4MKtYUCzg7uRuLiQjhcwBXPsbGuOxO+FAZnjZUOBiwWr6VQqRQyrDrlJiJ9ExHF5wluObJxVbHvw7LKR5tGN7zH0FPLGckEILXyopMzGJ57TQgP7k2npHLW2JEb9bBf6skqccShIjP6FCEx64ecPGr9+VkSukENenlVmeWxmXmW8X+Cp1JuXjc1mDkUCQfMMVJeG5UbKaGDrYeGefCXbsFMTpxf3kHnlCu4JUGQHdeqOOiO3vrR63Oe3VqUvwuM4A0cuPtX99ts4U=
